### ISSUE TITLE
Use var

### ISSUE THREAD

**Issue by EinboeckFranz** [jschwendtner17/Jeo#1]
double[,] arrC = new double[,] { { 2, 7, 1 }, { 3, -2, 8 }, { 1, 5, 3 } };

**Comment by littlegamer757** [comment]
wos fia var, einfoch des `double[,]` weg doa

**Comment by profiluefter** [comment]
🚀

**Comment by littlegamer757** [comment]
I hoff da Jan griagt do jetzt richtig vü Emails

**Comment by littlegamer757** [comment]
@SchneckchenAndy a nu, damid der a nu Mails griagt

**Comment by profiluefter** [comment]
du grenzt do de ondan teammitglieder (@SandroGreinecker und @ffischer18) aus

**Comment by littlegamer757** [comment]
eieiei, des duad ma gscheid load - sry @SandroGreinecker und @ffischer18

**Comment by SandroGreinecker** [comment]
I glaub i konns verzeihen, @littlegamer757 @EinboeckFranz @profiluefter

**Comment by ffischer18** [comment]
@profiluefter @littlegamer757 @SandroGreinecker @EinboeckFranz @jschwendtner17 bei mir leits durchgehend wos is des fia scheiß

**Comment by profiluefter** [comment]
@ffischer18 @SandroGreinecker @EinboeckFranz @jschwendtner17: es deafts olle ned an @SchneckchenAndy vergessn, der is scho gonz traurig wonnts eich des emoji bei @littlegamer757 seina obern nochricht onschauts

**Comment by littlegamer757** [comment]
> I glaub i konns verzeihen @littlegamer757 @EinboeckFranz @profiluefter

Gott sei Dank, sunst hätt i ma des nie verziehen @SandroGreinecker

**Comment by littlegamer757** [comment]
> @profiluefter @littlegamer757 @SandroGreinecker @EinboeckFranz @jschwendtner17 bei mir leits durchgehend wos is des fia scheiß

Is eh guad, zum Schluss hättst sunst nu wos verpasst von der Konversation @ffischer18

**Comment by littlegamer757** [comment]
@SchneckchenAndy bist du eher fia `var` oda `double` in dem Foi?

**Comment by SandroGreinecker** [comment]
@SchneckchenAndy wir warten! Oder ned? @littlegamer757 @profiluefter @EinboeckFranz @ffischer18 @jschwendtner17
